In [1]:
import pandas as pd
import numpy as np

In [ ]:
kospi20=['LG전자','이마트','기아차','SK하이닉스','한국전력',\
'현대백화점','셀트리온','KB금융','LG화학','아모레퍼시픽','기업은행','현대모비스','대우조선해양','GS건설',\
'S-Oil','삼성전자','현대차','대한항공','SK텔레콤'] #,'CJ제일제당'

for kospi in kospi20:
    v2_df = pd.read_csv("../../kospi_V2/data/{}_V2.csv".format(kospi))
    senti_df = pd.read_csv("../../Sentiment Analysis/Data/senti_{}.csv".format(kospi))

    del v2_df['Unnamed: 0.1']
    del v2_df['Unnamed: 0']

    rl_df = pd.merge(v2_df, senti_df, left_on=['Date'], right_on=['Date'], how='right')
    rl_df.to_csv("../../ReinforcementLearning/Data/{}_RL.csv".format(kospi), index=False)

SA V3로 만들기

In [47]:
v2_df = pd.read_csv("../../kospi_V2/data/CJ제일제당_V2.csv")
v2_df=v2_df[['date','open','high','low','close','volume','roe','per','pbr']]
senti_df = pd.read_csv("../../Sentiment Analysis/Data/senti_CJ제일제당_V3.csv")
senti_df = senti_df.rename({'Date':'date'},axis='columns')
rl_df = pd.merge(v2_df, senti_df, left_on=['date'], right_on=['date'], how='left')
rl_df = rl_df.fillna(0)

kospi = 'CJ'
rl_df.to_csv("../../frontback/StockTradingAgent/model/rltrader/data/v2/{}_RL_V2_withSA_2020.csv".format(kospi), index=False)

In [14]:
rl_df1.columns
kospi = 'samsung'
rl_df1.to_csv("../../frontback/StockTradingAgent/model/rltrader/data/v2/{}_RL_V2_withSA_2020.csv".format(kospi), index=False)

In [11]:
rl_df1.rename(columns={'Date':'date','Open':'open','High':'high','Low':'low','Close':'close','Volume':'volume','ROE':'roe','PER':'per','PBR':'pbr'}, inplace=True)

In [3]:
v1_df = pd.read_csv("../../kospi_V1/data/V1/삼성전자_V1.csv")
v1_df = v1_df[['Date','Open','High','Low','Close','Volume','ROE','PER','PBR']]
senti_df = pd.read_csv("../../Sentiment Analysis/Data/after/senti_CJ제일제당_V3.csv")
rl_df1 = pd.merge(v1_df, senti_df, left_on=['Date'], right_on=['Date'], how='left')
rl_df1 = rl_df1.fillna(0)

kospi = 'samsung'
rl_df1.to_csv("../../frontback/StockTradingAgent/model/rltrader/data/v2/{}_RL_V2_withSA.csv".format(kospi), index=False)

In [57]:
v1_df = pd.read_csv("../../kospi_V1/data/V1/CJ제일제당_V1.csv")
senti_df = pd.read_csv("../../Sentiment Analysis/Data/senti_CJ제일제당.csv")

del v1_df['Unnamed: 0']

rl_df = pd.merge(v1_df, senti_df, left_on=['Date'], right_on=['Date'], how='right')
kospi = 'CJ제일제당'
rl_df.to_csv("../../ReinforcementLearning/Data/{}_RL_V1_withSA.csv".format(kospi), index=False)

In [50]:
v2_df = pd.read_csv("../../kospi_V2/data/CJ제일제당_V2.csv")
senti_df = pd.read_csv("../../Sentiment Analysis/Data/senti_CJ제일제당.csv")

del v2_df['Unnamed: 0.1']
del v2_df['Unnamed: 0']

rl_df = pd.merge(v2_df, senti_df, left_on=['Date'], right_on=['Date'], how='right')
kospi = 'CJ제일제당'
rl_df.to_csv("../../ReinforcementLearning/Data/{}_RL_V2_withSA.csv".format(kospi), index=False)

In [58]:
v1_df

            Date    Open    High     Low   Close  Volume   ROE    PER   PBR
0     2014-01-02  277500  281000  276000  279500  101630  8.60  22.20  1.10
1     2014-01-03  278000  280000  274500  278500   78910  8.60  22.20  1.10
2     2014-01-06  277000  278000  272500  277000   42426  8.60  22.20  1.10
3     2014-01-07  274000  277000  273000  275500   49898  8.60  22.20  1.10
4     2014-01-08  274500  276500  272000  274500   42155  8.60  22.20  1.10
...          ...     ...     ...     ...     ...     ...   ...    ...   ...
1466  2019-12-23  244000  244500  240000  243500   33748  3.16  27.12  0.83
1467  2019-12-24  245500  245500  241500  242000   17060  3.16  27.12  0.83
1468  2019-12-26  244000  245000  241500  243000   32651  3.16  27.12  0.83
1469  2019-12-27  246000  251500  241000  250000   50065  3.16  27.12  0.83
1470  2019-12-30  252500  254500  250000  252500   31019  3.16  27.12  0.83

[1471 rows x 9 columns]